## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = "[$user]($style)@"
style_user = "bold #0087AF"
style_root = "bold #0087AF"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) "
style = "bold #0087AF"
trim_at = "-"
ssh_only = false
disabled = false


# Prompt: param 2 └─
[character]
success_symbol = "[❯](bold #5FD700)"
error_symbol = "(bold red)"

# Third param
[directory]
style = "#00AFFF"
truncation_length = 8
truncate_to_repo = false
truncation_symbol = '…/'

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[status]
style = "bold white"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
style = "#edd2ab"
symbol = "  "

[buf]
style = "#edd2ab"
symbol = " "

[c]
style = "#edd2ab"
symbol = " "

[conda]
style = "#edd2ab"
symbol = " "

[dart]
style = "#edd2ab"
symbol = " "

[docker_context]
symbol = " "
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
format = "via [$symbol$context]($style) "
style = "#edd2ab"
only_with_files = true
disabled = false

[elixir]
style = "#edd2ab"
symbol = " "

[elm]
style = "#edd2ab"
symbol = " "

[fossil_branch]
style = "#edd2ab"
symbol = " "

[git_branch]
symbol = " "
style = "#5FAF00"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "#5FAF00"

[git_status]
style = "#5FAF00"

[golang]
style = "#edd2ab"
symbol = " "

[guix_shell]
style = "#edd2ab"
symbol = " "

[haskell]
style = "#edd2ab"
symbol = " "

[haxe]
style = "#edd2ab"
symbol = "⌘ "

[hg_branch]
style = "#edd2ab"
symbol = " "

[java]
style = "#edd2ab"
symbol = " "

[julia]
style = "#edd2ab"
symbol = " "

[lua]
style = "#edd2ab"
symbol = " "

[memory_usage]
style = "#edd2ab"
symbol = "󰍛 "

[meson]
style = "#edd2ab"
symbol = "󰔷 "

[nim]
style = "#edd2ab"
symbol = "󰆥 "

[nix_shell]
style = "#edd2ab"
symbol = " "

[nodejs]
style = "#edd2ab"
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
style = "#edd2ab"
symbol = '📦 '

[pijul_channel]
style = "#edd2ab"
symbol = " "

[python]
style = "#edd2ab"
symbol = " "

[rlang]
style = "#edd2ab"
symbol = "󰟔 "

[ruby]
style = "#edd2ab"
symbol = " "

[rust]
style = "#edd2ab"
symbol = " "

[scala]
style = "#edd2ab"
symbol = " "

[spack]
style = "#edd2ab"
symbol = "🅢 "